#!/bin/bash

K8S_NAMESPACE=$(echo "$CONTEXT" | jq -r --arg default "$K8S_NAMESPACE" '
  .providers["container-orchestration"].cluster.namespace // $default
')

PROM_URL=$(echo "$CONTEXT" | jq -r '
  .providers["metrics"].server.url
')

if [[ -z "$PROM_URL" ]]; then
  echo "There is no prometheus provider configured. Please configure prometheus in Platform settings and try again." >&2
  exit 1
fi

while read -r line; do
  eval "$line"
done < <(echo "$CONTEXT" | jq -r '.arguments | to_entries[] | 
  if (.value | type) == "array" then 
    "export \(.key | ascii_upcase)=\(.value | join(","))" 
  else 
    "export \(.key | ascii_upcase)=\(.value)" 
  end')

if [[ -n "$METRIC" ]]; then
  export METRIC_NAME="$METRIC"
fi

export PROM_URL
export K8S_NAMESPACE
