#!/bin/bash

K8S_NAMESPACE=$(echo "$CONTEXT" | jq -r --arg default "$K8S_NAMESPACE" '
  .providers["container-orchestration"].cluster.namespace // $default
')

SCOPE_ID=$(echo "$CONTEXT" | jq -r '.scope.id')

JOB=$(kubectl get cronjob -n "$K8S_NAMESPACE" -l "scope_id=$SCOPE_ID" -o jsonpath="{.items[0].metadata.name}" 2>/dev/null || echo "")

kubectl create job --from="cronjob/$JOB" "$JOB-$(date +%s)"