#!/bin/bash

NRN=$(echo "$CONTEXT" | jq -r .entity_nrn)

DIMENSIONS=$(echo "$CONTEXT" | jq .service.dimensions)

CONTAINER_ORCHESTRATION=$(np category list --slug container-orchestration --format json | jq -r ".results[0].id")

PROVIDER_SPECS=$(np provider specification list --nrn "$NRN" --category "$CONTAINER_ORCHESTRATION" --format json | jq -r '[.results[].id] | join(",")')

DIMENSION_FILTER=$(echo "$DIMENSIONS" | jq -r 'to_entries | map("\(.key):\(.value)") | join(",")')

if [ -z "$DIMENSION_FILTER" ] || [ "$DIMENSION_FILTER" = "" ]; then
  PROVIDER=$(np provider list --nrn "$NRN" --specification_id "$PROVIDER_SPECS" --show_ascendants --format json | jq -r ".results[0].id")
else
  PROVIDER=$(np provider list --nrn "$NRN" --specification_id "$PROVIDER_SPECS" --show_ascendants --dimensions "$DIMENSION_FILTER" --format json | jq -r ".results[0].id")
fi

PROVIDER_DATA=$(np provider read --id "$PROVIDER" --format json)

K8S_NAMESPACE=$(echo "$PROVIDER_DATA" | jq -r .attributes.cluster.namespace)

ALB_NAME=$(echo "$PROVIDER_DATA" | jq -r --arg default "k8s-nullplatform-internet-facing" '
  .attributes.balancer.public_name // $default
')

echo "ALB: $ALB_NAME"
echo "Provider: $PROVIDER_DATA"

export K8S_NAMESPACE
export ALB_NAME