grafana:
  enabled: false

alertmanager:
  enabled: false

prometheusOperator:
  enabled: true

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
